[ubuntu_servers]
vm2-ubuntu


[debian_servers]
vm3-debian

[monitoring]
devops-study ansible_host=192.168.13.130 ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_user=leonlewiz
ansible_python_interpreter=/usr/bin/python3
