- name: Install cAdvisor.
  hosts: all:!monitoring
  become: yes
  tasks:

    - name: Install python3-requests
      ansible.builtin.apt:
        name: python3-requests
        state: present


    - name: Run cAdvisor
      community.docker.docker_container:
        name: cadvisor
        image: ghcr.io/google/cadvisor:0.54.0
        command:
          - "--docker_only=true"
          - "--store_container_labels=false"
          - "--disable_metrics=disk"
        state: started
        restart_policy: always
        privileged: true
        published_ports:
          - "8080:8080"
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /dev/kmsg:/dev/kmsg
