- name: Install Prometheus.
  hosts: localhost
  become: yes
  tasks:
    - name: Installing Prometheus.
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v3.14.0/prometheus-3.14.0.linux-amd64.tar.gz
        dest: /tmp
        checksum: sha256:https://github.com/prometheus/prometheus/releases/download/v3.14.0/sha256sums.txt

    - name: Create a directory
      ansible.builtin.file:
        path: /usr/local/bin/prometheus
        state: directory
        mode: '0755'

    - name: Extract
      ansible.builtin.unarchive:
        src: /tmp/prometheus-3.14.0.linux-amd64.tar.gz
        dest: /usr/local/bin/prometheus
        creates: /usr/local/bin/prometheus/prometheus
        remote_src: true
        extra_opts: ['--strip-components=1']

    - name: template
      template:
        src: ~/ansible-lab/group_vars/all/templates/prometheus.yml.j2
        dest: /usr/local/bin/prometheus/prometheus.yml
        mode: '0755'
      notify: Restart Prometheus

    - name: Copy rules.yml
      ansible.builtin.copy:
        src: ./files/rules.yml
        dest: /usr/local/bin/prometheus/rules.yml
        remote_src: true
      notify: Restart Prometheus

    - name: Create systemd unit
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/prometheus/prometheus --config.file=/usr/local/bin/prometheus/prometheus.yml --web.listen-address=0.0.0.0:9090
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart Prometheus

    - name: Enable and start Prometheus
      ansible.builtin.systemd:
        name: prometheus
        daemon_reload: true
        enabled: true
        state: started

  handlers:
    - name: Restart Prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
