- name: Install Grafana.
  hosts: monitoring
  become: yes
  tasks:
    - name: Installing Grafana.
      get_url:
        url: https://dl.grafana.com/oss/release/grafana-13.2.1.linux-amd64.tar.gz
        dest: /tmp/grafana-13.2.1.linux-amd64.tar.gz

    - name: Extract grafana
      ansible.builtin.unarchive:
        src: /tmp/grafana-13.2.1.linux-amd64.tar.gz
        dest: /opt
        remote_src: true
        creates: /opt/grafana-13.2.1

    - name: Symlink for stable path
      ansible.builtin.file:
        src: /opt/grafana-13.2.1
        dest: /opt/grafana
        state: link

    - name: Create systemd unit
      ansible.builtin.copy:
        dest: /etc/systemd/system/grafana.service
        content: |
          [Unit]
          Description=Grafana
          After=network.target

          [Service]
          ExecStart=/opt/grafana/bin/grafana server --homepath /opt/grafana
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Copy config for Grafana.
      ansible.builtin.copy:
        dest: /opt/grafana/conf/provisioning/datasources/prometheus.yml
        content: |
          apiVersion: 1

          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://localhost:9090
              isDefault: true
        notify: Restart Grafana 


    - name: Enable Grafana
      ansible.builtin.systemd:
        name: grafana
        daemon_reload: true
        enabled: true

handlers:
  - name: Restart Grafana
    ansible.builtin.systemd:
      name: grafana
      state: restarted
